default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: orto_development

test:
  <<: *default
  database: orto_test

production:
  <<: *default
  database: orto_production
  username: orto
  password: <%= ENV['ORTO_DATABASE_PASSWORD'] %>
